const PLACES=[
{id:'o1',type:'parking',name:'Parkplatz Basilika',lat:47.9410479,lon:10.2979736,total:60,fee:'kostenlos',meta:'Ottobeuren',source:'Markt Ottobeuren',sourceUrl:'https://www.ottobeuren.de/de/service/parkmoeglichkeiten/'},
{id:'o2',type:'parking',name:'Tiefgarage Luitpoldstraße',lat:47.9421,lon:10.2997,total:null,fee:'kostenpflichtig',meta:'Ottobeuren · Tiefgarage',source:'Markt Ottobeuren',sourceUrl:'https://www.ottobeuren.de/de/service/parkmoeglichkeiten/'},
{id:'o3',type:'parking',name:'Parkplatz Ulrichstraße',lat:47.9434,lon:10.3008,total:null,fee:'erste 90 Min. kostenlos, danach kostenpflichtig',meta:'Ottobeuren · Lademöglichkeiten',source:'Markt Ottobeuren',sourceUrl:'https://www.ottobeuren.de/de/service/parkmoeglichkeiten/'},
{id:'m1',type:'parking',name:'Parkhaus Bahnhofstraße',lat:47.9856,lon:10.1870,total:334,address:'Bahnhofstr. 5',height:'2,10 m',hours:'24/7',fee:'0,50 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen',sourceUrl:'https://stadtwerke-memmingen.de/produkte/parkhaeuser'},
{id:'m2',type:'parking',name:'Parkhaus Krautstraße',lat:47.9867,lon:10.1788,total:265,address:'Krautstr. 1',height:'2,00 m',hours:'24/7',fee:'0,70 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen',sourceUrl:'https://stadtwerke-memmingen.de/produkte/parkhaeuser'},
{id:'m3',type:'parking',name:'Tiefgarage Stadthalle',lat:47.9897,lon:10.1764,total:450,address:'Königsgraben',height:'2,10 m',hours:'24/7',fee:'0,70 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen',sourceUrl:'https://stadtwerke-memmingen.de/produkte/parkhaeuser'},
{id:'m4',type:'parking',name:'Parkhaus Schwesterstraße',lat:47.9842,lon:10.1805,total:335,address:'Schwesterstr. 17',height:'1,90 m',hours:'24/7',fee:'0,70 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen',sourceUrl:'https://stadtwerke-memmingen.de/produkte/parkhaeuser'},
{id:'m5',type:'parking',name:'Parkhaus Steinbogenstraße',lat:47.9826,lon:10.1818,total:330,address:'Steinbogenstr. 9',height:'2,10 m',hours:'24/7',fee:'0,60 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen',sourceUrl:'https://stadtwerke-memmingen.de/produkte/parkhaeuser'},
{id:'m6',type:'parking',name:'Parkhaus Siebendächer „Neue Schranne“',lat:47.9830,lon:10.1790,total:127,address:'Lindentorstraße 3',hours:'06:00–01:00',fee:'0,50 € / 20 Min. Mo–Sa',fee2:'Sonntag: 1 €/Std. · Abend/Nacht max. 2,50 € · Tagessatz max. 9 €',meta:'Memmingen',source:'Stadt Memmingen',sourceUrl:'https://www.memmingen.de/hier-leben/mobilitaet/parkmoeglichkeiten.html'},
{id:'m8',type:'parking',name:'Parkhaus Klinikum',lat:47.9941,lon:10.1748,total:390,address:'Bismarckstraße 23',hours:'05:30–21:00',fee:'1,00 € je Stunde (1.–6. Stunde)',fee2:'Tagessatz max. 6 € · Feiertage geöffnet',meta:'Memmingen',source:'Stadt Memmingen',sourceUrl:'https://www.memmingen.de/hier-leben/mobilitaet/parkmoeglichkeiten.html'}];
const PARK_RADIUS_KM=1,FUEL_RADIUS_KM=10,API='https://gregorbuerger--6c96ef50bea611f1b1051607ee4eb77e.web.val.run/';
let mode=localStorage.getItem('tp-mode')||'all',fuel=localStorage.getItem('tp-fuel')||'e10',markers=[],selected=null,target=null,targetMarker=null,searchTimer,fuelStations=[],fuelLoading=false,fuelError='',fuelRequestKey='',fuelFetchedAt=0;
const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[10.235,47.965],zoom:11.1,attributionControl:true});
function km(a,b,c,d){const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function parkingData(){let a=PLACES;if(target)a=a.map(x=>({...x,dist:km(target.lat,target.lon,x.lat,x.lon)})).filter(x=>x.dist<=PARK_RADIUS_KM).sort((a,b)=>a.dist-b.dist);return a}
function centerPoint(){if(target)return{lat:target.lat,lon:target.lon};const c=map.getCenter();return{lat:c.lat,lon:c.lng}}
function isOpen(x){if(!x.hours)return null;if(x.hours==='24/7')return true;const now=new Date(),mins=now.getHours()*60+now.getMinutes(),[a,b]=x.hours.split('–'),toM=s=>{const[h,m]=s.split(':').map(Number);return h*60+m},start=toM(a),end=toM(b);return end<start?(mins>=start||mins<end):(mins>=start&&mins<end)}
function hoursText(x){if(!x.hours)return '';return x.hours==='24/7'?'24 h geöffnet':`geöffnet ${x.hours} Uhr`}
function price(v){return typeof v==='number'?v.toFixed(3).replace('.',',')+' €':'–'}
function fuelName(){return fuel==='e5'?'E5':fuel==='diesel'?'Diesel':'E10'}
async function loadFuel(force=false){if(mode==='parking')return;const c=centerPoint(),key=`${c.lat.toFixed(3)}:${c.lon.toFixed(3)}:${fuel}`;if(!force&&key===fuelRequestKey&&Date.now()-fuelFetchedAt<60000)return;fuelRequestKey=key;fuelLoading=true;fuelError='';render();try{const u=new URL(API);u.searchParams.set('lat',c.lat);u.searchParams.set('lng',c.lon);u.searchParams.set('radius',FUEL_RADIUS_KM);u.searchParams.set('fuel',fuel);const r=await fetch(u,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Abfrage fehlgeschlagen');fuelStations=(j.stations||[]).map(x=>({...x,type:'fuel',lat:+x.lat,lon:+x.lng,dist:+x.distance,price:x.selectedPrice}));fuelFetchedAt=Date.now()}catch(e){fuelStations=[];fuelError=e.message||'Live-Daten konnten nicht geladen werden.'}finally{fuelLoading=false;render()}}
function render(){markers.forEach(m=>m.remove());markers=[];const parks=mode==='fuel'?[]:parkingData(),fuels=mode==='parking'?[]:fuelStations;let count=parks.length+fuels.length,label=mode==='fuel'?`${fuels.length} Tankstellen`:mode==='parking'?`${parks.length} ${parks.length===1?'Parkmöglichkeit':'Parkmöglichkeiten'}`:`${count} Ergebnisse`;
 document.getElementById('resultCount').textContent=label;document.getElementById('miniCount').textContent=label;const sub=mode==='fuel'?`${FUEL_RADIUS_KM} km · ${fuelName()}`:target?`Parken ${PARK_RADIUS_KM} km${mode==='all'?' · Tanken 10 km':''}`:'in der Kartenansicht';document.getElementById('dockSubtitle').textContent=sub;document.getElementById('areaText').textContent=' '+sub;const cards=document.getElementById('cards');cards.innerHTML='';
 parks.forEach(x=>{const el=document.createElement('div');el.className='marker parking';el.textContent='P';markers.push(new maplibregl.Marker({element:el}).setLngLat([x.lon,x.lat]).addTo(map));el.onclick=()=>selectParking(x.id);const d=x.dist!=null?` · ${x.dist<1?Math.round(x.dist*1000)+' m':x.dist.toFixed(1).replace('.',',')+' km'} zum Ziel`:'';const open=isOpen(x),status=open==null?'':`<span class="open-state ${open?'open':'closed'}">${open?'● Jetzt geöffnet':'● Jetzt geschlossen'}</span>`,details=[x.total?`${x.total} Stellplätze`:null,x.height?`Einfahrt ${x.height}`:null].filter(Boolean).join(' · ');const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-head"><div><div class="type">🅿 Parken</div><div class="name">${x.name}</div><div class="distance">${details}${d}</div></div></div>${status}<div class="parking-hours">${hoursText(x)}</div><div class="parking-fee"><strong>${x.fee}</strong>${x.fee2?`<span>${x.fee2}</span>`:''}</div><div class="meta">${x.address?x.address+' · ':''}${x.source}</div>${x.sourceUrl?`<a class="source-link" href="${x.sourceUrl}" target="_blank" rel="noopener noreferrer">Quelle: ${x.source} ↗</a>`:''}`;card.onclick=e=>{if(!e.target.closest('a'))selectParking(x.id)};cards.appendChild(card)});
 fuels.forEach(x=>{const el=document.createElement('div');el.className='marker fuel-marker';el.innerHTML=`<span>${price(x.price).replace(' €','')}</span><small>${fuelName()}</small>`;markers.push(new maplibregl.Marker({element:el}).setLngLat([x.lon,x.lat]).addTo(map));el.onclick=()=>selectFuel(x.id);const card=document.createElement('article');card.className='card fuel-card';card.innerHTML=`<div class="card-head"><div><div class="type">⛽ ${fuelName()}</div><div class="name">${x.name}</div><div class="distance">${x.distance.toFixed(1).replace('.',',')} km · ${x.street||''} ${x.houseNumber||''}, ${x.place||''}</div></div><div class="fuel-price">${price(x.price)}<small>/l</small></div></div><span class="open-state ${x.isOpen?'open':'closed'}">${x.isOpen?'● Geöffnet':'● Geschlossen'}</span><div class="meta">MTS-K über Tankerkönig · CC BY 4.0</div>`;card.onclick=()=>selectFuel(x.id);cards.appendChild(card)});
 if(fuelLoading&&mode!=='parking')cards.insertAdjacentHTML('beforeend','<article class="card empty-card"><div class="type">⛽ Live-Daten</div><div class="name">Tankstellen werden geladen …</div></article>');if(fuelError&&mode!=='parking')cards.insertAdjacentHTML('beforeend',`<article class="card empty-card"><div class="type">⛽ Live-Daten</div><div class="name">Tankstellen derzeit nicht verfügbar</div><div class="meta">${fuelError}</div></article>`);if(!cards.children.length&&!fuelLoading)cards.innerHTML='<article class="card empty-card"><div class="name">Keine Ergebnisse in diesem Bereich</div></article>'}
function showParkingDetail(x){const d=x.dist!=null?(x.dist<1?Math.round(x.dist*1000)+' m zum Ziel':x.dist.toFixed(1).replace('.',',')+' km zum Ziel'):'',open=isOpen(x),details=[x.total?`${x.total} Stellplätze`:null,x.height?`Einfahrt ${x.height}`:null,d].filter(Boolean),box=document.getElementById('placeDetail');box.className='place-detail';box.innerHTML=`<div class="detail-top"><div><div class="type">🅿 PARKEN</div><div class="detail-title">${x.name}</div><div class="detail-sub">${x.address||x.meta||''}</div></div><button class="detail-close">×</button></div><div class="detail-row">${open==null?'':`<span class="pill ${open?'open':'closed'}">${open?'● Geöffnet':'● Geschlossen'}</span>`}${details.map(v=>`<span class="pill">${v}</span>`).join('')}</div><div class="detail-fee"><strong>${x.fee||''}</strong></div><div class="detail-extra">${hoursText(x)}${x.fee2?`<br>${x.fee2}`:''}<br>Keine Live-Belegung verfügbar.</div><div class="detail-actions"><button class="detail-more">Details</button>${x.sourceUrl?`<a class="detail-source" href="${x.sourceUrl}" target="_blank" rel="noopener noreferrer">Quelle ↗</a>`:''}</div>`;bindDetail(box)}
function showFuelDetail(x){const box=document.getElementById('placeDetail'),addr=[x.street,x.houseNumber].filter(Boolean).join(' ')+' · '+[x.postCode,x.place].filter(Boolean).join(' ');box.className='place-detail';box.innerHTML=`<div class="detail-top"><div><div class="type">⛽ ${fuelName()}</div><div class="detail-title">${x.name}</div><div class="detail-sub">${addr}</div></div><button class="detail-close">×</button></div><div class="detail-row"><span class="pill ${x.isOpen?'open':'closed'}">${x.isOpen?'● Geöffnet':'● Geschlossen'}</span><span class="pill">${x.distance.toFixed(1).replace('.',',')} km</span></div><div class="detail-fuel-price">${price(x.price)} <small>/ Liter</small></div><div class="detail-extra">E5: ${price(x.prices?.e5)}<br>E10: ${price(x.prices?.e10)}<br>Diesel: ${price(x.prices?.diesel)}<br><br>Daten: MTS-K über Tankerkönig · CC BY 4.0 · ausschließlich Verbraucherinformation.</div><div class="detail-actions"><button class="detail-more">Details</button><a class="detail-source" href="https://creativecommons.tankerkoenig.de/" target="_blank" rel="noopener noreferrer">Tankerkönig ↗</a></div>`;bindDetail(box)}
function bindDetail(box){box.querySelector('.detail-close').onclick=()=>{box.classList.add('hidden');selected=null};box.querySelector('.detail-more').onclick=()=>{box.classList.toggle('expanded');box.querySelector('.detail-more').textContent=box.classList.contains('expanded')?'Weniger':'Details'}}
function selectParking(id){selected=id;const x=parkingData().find(v=>v.id===id)||PLACES.find(v=>v.id===id);setSheet(true);map.easeTo({center:[x.lon,x.lat],zoom:15,duration:450,padding:{bottom:150}});showParkingDetail(x)}
function selectFuel(id){selected=id;const x=fuelStations.find(v=>v.id===id);if(!x)return;setSheet(true);map.easeTo({center:[x.lon,x.lat],zoom:14.5,duration:450,padding:{bottom:150}});showFuelDetail(x)}
function setTarget(t){selected=null;document.getElementById('placeDetail').classList.add('hidden');setSheet(true);target=t;if(targetMarker)targetMarker.remove();const el=document.createElement('div');el.className='target-marker';el.textContent='⌖';targetMarker=new maplibregl.Marker({element:el}).setLngLat([t.lon,t.lat]).addTo(map);document.getElementById('targetInfo').classList.remove('hidden');document.getElementById('targetInfo').innerHTML=`<strong>Ziel</strong><span>${t.label} · Parken ${PARK_RADIUS_KM} km · Tanken ${FUEL_RADIUS_KM} km</span>`;map.flyTo({center:[t.lon,t.lat],zoom:14});render();loadFuel(true)}
async function geocode(q){const box='10.08,48.06,10.36,47.88',u=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=10&countrycodes=de&viewbox=${box}&bounded=1&q=${encodeURIComponent(q)}`,r=await fetch(u,{headers:{'Accept-Language':'de'}});if(!r.ok)throw Error();return normalizeSuggestions(await r.json())}
function suggestionParts(v){const a=v.address||{},road=a.road||a.pedestrian||a.residential||a.path||'',house=a.house_number||'',city=a.town||a.city||a.village||a.municipality||a.county||'',postcode=a.postcode||'';let title=[road,house].filter(Boolean).join(' ').trim();if(!title)title=(v.name||v.display_name.split(',')[0]||'Adresse').trim();let subtitle=[postcode,city].filter(Boolean).join(' ').trim();return{title,subtitle}}
function normalizeSuggestions(list){const out=[];for(const v of list){const p=suggestionParts(v),lat=+v.lat,lon=+v.lon,same=out.some(x=>{const xp=suggestionParts(x),sameLabel=(xp.title+'|'+xp.subtitle).toLowerCase()===(p.title+'|'+p.subtitle).toLowerCase(),near=Math.abs(+x.lat-lat)<.00045&&Math.abs(+x.lon-lon)<.00065;return sameLabel||near});if(!same)out.push(v);if(out.length===4)break}return out}
function showSuggestions(list){const s=document.getElementById('suggestions');s.innerHTML='';list.forEach(v=>{const p=suggestionParts(v),b=document.createElement('button');b.type='button';b.innerHTML=`<strong>${p.title}</strong>${p.subtitle?`<small>${p.subtitle}</small>`:''}`;b.onclick=()=>{s.innerHTML='';addressInput.value=p.title;endSearch();setTarget({lat:+v.lat,lon:+v.lon,label:[p.title,p.subtitle].filter(Boolean).join(', ')})};s.appendChild(b)})}
const addressInput=document.getElementById('addressInput');addressInput.addEventListener('focus',()=>{document.body.classList.add('search-active');document.querySelector('.searchbox').classList.add('searching')});function endSearch(){document.body.classList.remove('search-active');document.querySelector('.searchbox').classList.remove('searching');addressInput.blur()}
addressInput.addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();if(q.length<3){showSuggestions([]);return}searchTimer=setTimeout(async()=>{try{showSuggestions(await geocode(q))}catch{}},650)});document.getElementById('addressForm').onsubmit=async e=>{e.preventDefault();const q=addressInput.value.trim();if(q)try{const a=await geocode(q);if(a[0]){const p=suggestionParts(a[0]);endSearch();setTarget({lat:+a[0].lat,lon:+a[0].lon,label:[p.title,p.subtitle].filter(Boolean).join(', ')})}}catch{}};
document.getElementById('clearSearch').onclick=()=>{addressInput.value='';showSuggestions([]);target=null;if(targetMarker)targetMarker.remove();targetMarker=null;document.getElementById('targetInfo').classList.add('hidden');render();loadFuel(true)};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;localStorage.setItem('tp-mode',mode);document.getElementById('fuelFilter').style.display=mode==='fuel'?'flex':'none';selected=null;document.getElementById('placeDetail').classList.add('hidden');render();if(mode!=='parking')loadFuel()});document.querySelectorAll('.fuel-chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.fuel-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');fuel=b.dataset.fuel;localStorage.setItem('tp-fuel',fuel);fuelRequestKey='';render();loadFuel(true)});
function restorePrefs(){document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.getElementById('fuelFilter').style.display=mode==='fuel'?'flex':'none';document.querySelectorAll('.fuel-chip').forEach(b=>b.classList.toggle('active',b.dataset.fuel===fuel))}restorePrefs();
const sheetContent=document.getElementById('sheetContent'),sheetMini=document.getElementById('sheetMini'),sheetToggle=document.getElementById('sheetToggle');function setSheet(minimized){sheetContent.classList.toggle('hidden',minimized);sheetMini.classList.toggle('hidden',!minimized)}sheetToggle.onclick=()=>setSheet(true);sheetMini.onclick=()=>setSheet(false);
const sh=document.getElementById('searchHere');map.on('dragend',()=>sh.classList.add('visible'));sh.onclick=()=>{sh.classList.remove('visible');target=null;if(targetMarker)targetMarker.remove();targetMarker=null;document.getElementById('targetInfo').classList.add('hidden');render();loadFuel(true)};document.getElementById('locateBtn').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{selected=null;target={lat:p.coords.latitude,lon:p.coords.longitude,label:'Mein Standort'};document.getElementById('placeDetail').classList.add('hidden');setSheet(true);if(targetMarker)targetMarker.remove();targetMarker=null;document.getElementById('targetInfo').classList.remove('hidden');document.getElementById('targetInfo').innerHTML=`<strong>Mein Standort</strong><span>Parken ${PARK_RADIUS_KM} km · Tanken ${FUEL_RADIUS_KM} km</span>`;map.flyTo({center:[target.lon,target.lat],zoom:14});render();loadFuel(true)},()=>alert('Standort konnte nicht ermittelt werden.'));
map.on('load',()=>{render();if(mode!=='parking')loadFuel()});
function showInfo(){const box=document.getElementById('placeDetail');box.className='place-detail expanded';box.innerHTML=`<div class="detail-top"><div><div class="type">INFO</div><div class="detail-title">Datenquellen</div></div><button class="detail-close">×</button></div><div class="info-copy"><strong>Kraftstoffpreise & Tankstellen</strong><br>MTS-K, bereitgestellt über Tankerkönig · CC BY 4.0. Verwendung ausschließlich zur Verbraucherinformation.<br><a href="https://creativecommons.tankerkoenig.de/" target="_blank" rel="noopener noreferrer">Tankerkönig ↗</a><br><br><strong>Parkplätze</strong><br>Markt Ottobeuren, Stadt Memmingen und Stadtwerke Memmingen. Die jeweilige Quelle ist am Eintrag verlinkt.<br><br><strong>Karte</strong><br>OpenFreeMap / OpenStreetMap.</div>`;box.querySelector('.detail-close').onclick=()=>box.classList.add('hidden')}
document.getElementById('infoBtn').onclick=showInfo;
async function checkForUpdate(manual=false){const status=document.getElementById('updateStatus');if(manual){status.textContent='Suche nach Update …';status.classList.remove('hidden')}try{if(!('serviceWorker'in navigator))return;const reg=await navigator.serviceWorker.getRegistration()||await navigator.serviceWorker.register('./sw.js');await reg.update();if(manual){status.textContent='v3.1 ist aktuell.';setTimeout(()=>status.classList.add('hidden'),2200)}}catch{if(manual)status.textContent='Updateprüfung fehlgeschlagen.'}}document.getElementById('updateBtn').onclick=()=>checkForUpdate(true);if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{reg.update();setInterval(()=>reg.update(),30*60*1000)});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!window.__reloading){window.__reloading=true;location.reload()}})}
