const PLACES=[
{id:'o1',type:'parking',name:'Parkplatz Basilika',lat:47.9410479,lon:10.2979736,total:60,fee:'kostenlos',meta:'Ottobeuren',source:'Markt Ottobeuren'},
{id:'o2',type:'parking',name:'Tiefgarage Luitpoldstraße',lat:47.9421,lon:10.2997,total:null,fee:'kostenpflichtig',meta:'Ottobeuren · Tiefgarage',source:'Markt Ottobeuren'},
{id:'o3',type:'parking',name:'Parkplatz Ulrichstraße',lat:47.9434,lon:10.3008,total:null,fee:'erste 90 Min. kostenlos, danach kostenpflichtig',meta:'Ottobeuren · Lademöglichkeiten',source:'Markt Ottobeuren'},
{id:'m1',type:'parking',name:'Parkhaus Bahnhofstraße',lat:47.9856,lon:10.1870,total:334,address:'Bahnhofstr. 5',height:'2,10 m',hours:'24/7',fee:'0,50 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen'},
{id:'m2',type:'parking',name:'Parkhaus Krautstraße',lat:47.9867,lon:10.1788,total:265,address:'Krautstr. 1',height:'2,00 m',hours:'24/7',fee:'0,70 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen'},
{id:'m3',type:'parking',name:'Tiefgarage Stadthalle',lat:47.9897,lon:10.1764,total:450,address:'Königsgraben',height:'2,10 m',hours:'24/7',fee:'0,70 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen'},
{id:'m4',type:'parking',name:'Parkhaus Schwesterstraße',lat:47.9842,lon:10.1805,total:335,address:'Schwesterstr. 17',height:'1,90 m',hours:'24/7',fee:'0,70 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen'},
{id:'m5',type:'parking',name:'Parkhaus Steinbogenstraße',lat:47.9826,lon:10.1818,total:330,address:'Steinbogenstr. 9',height:'2,10 m',hours:'24/7',fee:'0,60 € / 30 Min. (8–19 Uhr) · max. 5 €',fee2:'19–8 Uhr: 0,50 €/Std., max. 2 € · Sonn-/Feiertag: 1 € · Tagessatz Mo–Sa max. 9 €',meta:'Memmingen',source:'Stadtwerke Memmingen'},
{id:'m6',type:'parking',name:'Parkhaus Siebendächer „Neue Schranne“',lat:47.9830,lon:10.1790,total:127,address:'Lindentorstraße 3',hours:'06:00–01:00',fee:'0,50 € / 20 Min. Mo–Sa',fee2:'Sonntag: 1 €/Std. · Abend/Nacht max. 2,50 € · Tagessatz max. 9 €',meta:'Memmingen',source:'Stadt Memmingen'},
{id:'m8',type:'parking',name:'Parkhaus Klinikum',lat:47.9941,lon:10.1748,total:390,address:'Bismarckstraße 23',hours:'05:30–21:00',fee:'1,00 € je Stunde (1.–6. Stunde)',fee2:'Tagessatz max. 6 € · Feiertage geöffnet',meta:'Memmingen',source:'Stadt Memmingen'}]
let mode='all',fuel='e10',markers=[],selected=null,target=null,targetMarker=null,searchTimer;
const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[10.235,47.965],zoom:11.1,attributionControl:true});
function km(a,b,c,d){const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p;const q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function data(){let a=PLACES.filter(x=>mode==='all'||x.type===mode);if(target)a=a.map(x=>({...x,dist:km(target.lat,target.lon,x.lat,x.lon)})).sort((a,b)=>a.dist-b.dist);return a}
function isOpen(x){if(!x.hours)return null;if(x.hours==='24/7')return true;const now=new Date(),mins=now.getHours()*60+now.getMinutes();const [a,b]=x.hours.split('–');const toM=s=>{const [h,m]=s.split(':').map(Number);return h*60+m};const start=toM(a),end=toM(b);return end<start?(mins>=start||mins<end):(mins>=start&&mins<end)}
function hoursText(x){if(!x.hours)return '';return x.hours==='24/7'?'24 h geöffnet':`geöffnet ${x.hours} Uhr`}
function render(){markers.forEach(m=>m.remove());markers=[];const a=data();document.getElementById('resultCount').textContent=`${a.length} Orte`;const cards=document.getElementById('cards');cards.innerHTML='';if(mode==='fuel'){cards.innerHTML='<article class="card empty-card"><div class="type">⛽ Tankstellen</div><div class="name">Noch keine Live-Daten</div><div class="meta">Der Val-Town-Endpunkt ist vorbereitet. Tankstellen erscheinen hier, sobald der Tankerkönig-Key aktiv ist.</div></article>';return}a.forEach(x=>{const el=document.createElement('div');el.className='marker parking';el.textContent='P';markers.push(new maplibregl.Marker({element:el}).setLngLat([x.lon,x.lat]).addTo(map));el.onclick=()=>select(x.id,true);const d=x.dist!=null?` · ${x.dist<1?Math.round(x.dist*1000)+' m':x.dist.toFixed(1).replace('.',',')+' km'} zum Ziel`:'';const open=isOpen(x);const status=open==null?'':`<span class="open-state ${open?'open':'closed'}">${open?'● Jetzt geöffnet':'● Jetzt geschlossen'}</span>`;const details=[x.total?`${x.total} Stellplätze`:null,x.height?`Einfahrt ${x.height}`:null].filter(Boolean).join(' · ');const card=document.createElement('article');card.className='card'+(selected===x.id?' selected':'');card.dataset.id=x.id;card.innerHTML=`<div class="card-head"><div><div class="type">🅿 Parken</div><div class="name">${x.name}</div><div class="distance">${details}${d}</div></div><div class="availability">–<small> keine Live-Belegung</small></div></div>${status}<div class="parking-hours">${hoursText(x)}</div><div class="parking-fee"><strong>${x.fee}</strong>${x.fee2?`<span>${x.fee2}</span>`:''}</div><div class="meta">${x.address?x.address+' · ':''}${x.source}</div>`;card.onclick=()=>select(x.id,false);cards.appendChild(card)})}
function select(id,scroll){selected=id;const x=PLACES.find(v=>v.id===id);map.easeTo({center:[x.lon,x.lat],zoom:15,duration:450});render();if(scroll)setTimeout(()=>document.querySelector(`.card[data-id="${id}"]`)?.scrollIntoView({behavior:'smooth',inline:'center'}),50)}
function setTarget(t){target=t;if(targetMarker)targetMarker.remove();const el=document.createElement('div');el.className='target-marker';el.textContent='⌖';targetMarker=new maplibregl.Marker({element:el}).setLngLat([t.lon,t.lat]).addTo(map);document.getElementById('targetInfo').classList.remove('hidden');document.getElementById('targetInfo').innerHTML=`<strong>Parken am Ziel</strong><span>${t.label}</span>`;map.flyTo({center:[t.lon,t.lat],zoom:14});mode='parking';document.querySelectorAll('.seg').forEach(b=>b.classList.toggle('active',b.dataset.mode==='parking'));document.getElementById('fuelFilter').style.display='none';render()}
async function geocode(q){const box='10.08,48.06,10.36,47.88';const u=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=de&viewbox=${box}&bounded=1&q=${encodeURIComponent(q)}`;const r=await fetch(u,{headers:{'Accept-Language':'de'}});if(!r.ok)throw Error();return r.json()}
function showSuggestions(list){const s=document.getElementById('suggestions');s.innerHTML='';list.forEach(v=>{const b=document.createElement('button');b.type='button';b.textContent=v.display_name;b.onclick=()=>{s.innerHTML='';document.getElementById('addressInput').value=v.display_name.split(',').slice(0,3).join(',');setTarget({lat:+v.lat,lon:+v.lon,label:v.display_name})};s.appendChild(b)})}
document.getElementById('addressInput').addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();if(q.length<3){showSuggestions([]);return}searchTimer=setTimeout(async()=>{try{showSuggestions(await geocode(q))}catch{}},650)});
document.getElementById('addressForm').onsubmit=async e=>{e.preventDefault();const q=document.getElementById('addressInput').value.trim();if(q)try{const a=await geocode(q);if(a[0])setTarget({lat:+a[0].lat,lon:+a[0].lon,label:a[0].display_name})}catch{}};
document.getElementById('clearSearch').onclick=()=>{document.getElementById('addressInput').value='';showSuggestions([]);target=null;if(targetMarker)targetMarker.remove();targetMarker=null;document.getElementById('targetInfo').classList.add('hidden');render()};
document.querySelectorAll('.seg').forEach(b=>b.onclick=()=>{document.querySelectorAll('.seg').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;document.getElementById('fuelFilter').style.display=mode==='parking'?'none':'flex';selected=null;render()});document.querySelectorAll('.fuel-chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.fuel-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');fuel=b.dataset.fuel;render()});
const sh=document.getElementById('searchHere');map.on('dragend',()=>sh.classList.add('visible'));sh.onclick=()=>{sh.classList.remove('visible');render()};document.getElementById('locateBtn').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>map.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:14}),()=>alert('Standort konnte nicht ermittelt werden.'));map.on('load',render);
async function checkForUpdate(manual=false){const status=document.getElementById('updateStatus');if(manual){status.textContent='Suche nach Update …';status.classList.remove('hidden')}try{if(!('serviceWorker' in navigator)){if(manual)status.textContent='Updateprüfung ist in diesem Browser nicht verfügbar.';return}const reg=await navigator.serviceWorker.getRegistration()||await navigator.serviceWorker.register('./sw.js');await reg.update();if(reg.waiting){status.innerHTML='Neue Version verfügbar. <button id="reloadUpdate" type="button">Jetzt aktualisieren</button>';status.classList.remove('hidden');document.getElementById('reloadUpdate').onclick=()=>location.reload();return}if(manual){status.textContent='v2.4 ist aktuell.';setTimeout(()=>status.classList.add('hidden'),2200)}}catch(e){if(manual)status.textContent='Updateprüfung fehlgeschlagen.'}}
document.getElementById('updateBtn').onclick=()=>checkForUpdate(true);
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{reg.update();setInterval(()=>reg.update(),30*60*1000);reg.addEventListener('updatefound',()=>{const w=reg.installing;if(w)w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller){const status=document.getElementById('updateStatus');status.innerHTML='Neue Version verfügbar. <button id="reloadUpdate" type="button">Jetzt aktualisieren</button>';status.classList.remove('hidden');document.getElementById('reloadUpdate').onclick=()=>location.reload()}})})});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!window.__reloading){window.__reloading=true;location.reload()}})}
